name: Deploy Expense Tracker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on Host Machine
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/expense-tracker

            git pull origin main

            echo '${{ secrets.GCP_CREDENTIALS_JSON }}' > credentials.json

            docker stop expense-tracker || true
            docker rm expense-tracker || true

            docker build -t expense-tracker .

            docker run -d \
              --name expense-tracker \
              -p 8501:8501 \
              expense-tracker