name: Deploy Expense Tracker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # Changed this to self-hosted so it runs on your actual server
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create credentials.json from Secret
        # Using a safer EOF method to prevent JSON formatting errors
        run: |
          cat <<EOF > credentials.json
          ${{ secrets.GCP_CREDENTIALS_JSON }}
          EOF
          
      - name: Build Docker Image
        run: docker build -t expense-tracker .
        
      - name: Stop Old Container
        run: |
          docker stop expense-tracker || true
          docker rm expense-tracker || true

      - name: Build and Start New Container
        run: docker run -d --name expense-tracker -p 8501:8501 expense-tracker

      - name: Clean up unused Docker images
        run: docker image prune -f